# Created by: Kirn Gill II <segin2005@gmail.com>
# $FreeBSD: $

PORTNAME=	boxfs
PORTVERSION=	0.7
CATEGORIES=	sysutils
MASTER_SITES=	GOOGLE_CODE
PKGNAMEPREFIX=	fusefs-
EXTRACT_SUFX=	.tgz

MAINTAINER=	segin2005@gmail.com
COMMENT=	FUSE module for mounting Box.com accounts as local filesystems

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING


.include <bsd.port.mk>
