#define DEF_BG                  "darkred"
#define DEF_IBG                 "dimgray"
#define DEF_FG                  "lightgray"
#define DEF_IFG                 "lightgray"
#define DEF_FONT                "variable"
#define DEF_BUTTON1            "move"
#define DEF_BUTTON2            ""
#define DEF_BUTTON3            "resize"
#define DEF_BUTTON4            "raise"
#define DEF_BUTTON5            "lower"
#define DEF_MOUSEMOD            "mod1"
#define DEF_KEY_NEXT            "mod1 Tab"
#define DEF_KEY_PREV            "mod1 shift Tab"
#define DEF_KEY_ICONIFY         "control mod1 s"
#define DEF_KEY_MAXIMISE        "control mod1 x"
#define DEF_KEY_CLOSE           "control mod1 q"
#define DEF_KEY_TOPLEFT         "control mod1 y"
#define DEF_KEY_TOPRIGHT        "control mod1 u"
#define DEF_KEY_BOTTOMLEFT      "control mod1 b"
#define DEF_KEY_BOTTOMRIGHT     "control mod1 n"
#define DEF_BW                  4
#define DEF_SNAP                5
#define MINSIZE                 5
#define CFGFN                   ".matwmrc"
#define NO_TITLE                "-"

