#define DEF_BG                  "darkred"
#define DEF_IBG                 "dimgray"
#define DEF_FG                  "lightgray"
#define DEF_IFG                 "lightgray"
#define DEF_FONT                "variable"
#define DEF_CBUTTON1            "move"
#define DEF_CBUTTON2            ""
#define DEF_CBUTTON3            "resize"
#define DEF_CBUTTON4            "lower"
#define DEF_CBUTTON5            "raise"
#define DEF_IBUTTON1            "restore"
#define DEF_IBUTTON2            ""
#define DEF_IBUTTON3            ""
#define DEF_IBUTTON4            "lower"
#define DEF_IBUTTON5            "raise"
#define DEF_MOUSEMOD            "Alt_L"
#define DEF_KEY_NEXT            "Alt_L Tab"
#define DEF_KEY_PREV            "Alt_L Shift_L Tab"
#define DEF_KEY_NEXT_ICON       "Alt_L a"
#define DEF_KEY_PREV_ICON       "Alt_L Shift_L a"
#define DEF_KEY_ICONIFY         "Alt_L s"
#define DEF_KEY_MAXIMISE        "Alt_L x"
#define DEF_KEY_CLOSE           "Alt_L q"
#define DEF_KEY_TOPLEFT         "Alt_L y"
#define DEF_KEY_TOPRIGHT        "Alt_L u"
#define DEF_KEY_BOTTOMLEFT      "Alt_L b"
#define DEF_KEY_BOTTOMRIGHT     "Alt_L n"
#define DEF_BW                  4
#define DEF_H_ICON_COUNT        6
#define MINSIZE                 5
#define CFGFN                   ".matwmrc"

