enum {
  NET_SUPPORTED,
  NET_SUPPORTING_WM_CHECK,
  NET_WM_NAME,
  NET_NUMBER_OF_DESKTOPS,
  NET_DESKTOP_GEOMETRY,
  NET_DESKTOP_VIEWPORT,
  NET_WORKAREA,
  NET_WM_STRUT,
  NET_WM_STRUT_PARTIAL,
  NET_CURRENT_DESKTOP,
  NET_DESKTOP_NAMES,
  NET_CLIENT_LIST,
  NET_CLIENT_LIST_STACKING,
  NET_ACTIVE_WINDOW,
  NET_WM_STATE,
  NET_CLOSE_WINDOW,
  NET_WM_WINDOW_TYPE,
  NET_WM_WINDOW_TYPE_DESKTOP,
  NET_WM_WINDOW_TYPE_DOCK,
  EWMH_ATOM_COUNT
};

