#
# mcres Makefile
# 

CC	:= gcc
CFLAGS	:= -m32
OBJEXT	:= .o
BINEXT	:= .exe
PROG	:= mcres


SOURCES	:= mcres.c
OBJS	:= $(SOURCES:.c=$(OBJEXT))

all: $(PROG)$(BINEXT)

$(PROG)$(BINEXT): $(OBJS)
