OBJS += string/strlen.o string/bcmp.o string/bcopy.o string/bzero.o    \
string/ffs.o string/memccpy.o string/memchr.o string/memcmp.o          \
string/memrchr.o string/memset.o string/rindex.o string/stpcpy.o       \
string/stpncpy.o string/strcasecmp.o string/strcat.o string/strchr.o   \
string/strcmp.o

# not added: bm.o
