OBJS += string/bcmp.o string/bcopy.o string/bzero.o string/ffs.o       \
string/index.o string/memccpy.o string/memchr.o string/memcmp.o        \
string/memrchr.o string/memset.o string/rindex.o string/stpcpy.o       \
string/stpncpy.o string/strcasecmp.o string/strcat.o string/strchr.o   \
string/strcmp.o string/strcoll.o string/strcpy.o string/strcspn.o      \
string/strlcat.o string/strlcpy.o string/strlen.o string/strncat.o     \
string/strncmp.o string/strncpy.o string/strnlen.o string/strpbrk.o    \
string/strsep.o string/strspn.o string/strstr.o string/strtok.o        \
string/strxfrm.o string/swab.o string/timingsafe_bcmp.o                \
string/memcpy.o string/memmove.o string/strchr.o string/strrchr.o

# not added yet due to problems: bm.o strdup.o strerror.o strerror_r.o
#  strmode.o strndup.o strsignal.o w*.o
