 define __config 0x2007

 define W 0x0000
 define F 0x0001

 define INDF 0x0000
 define TMR0 0x0001
 define PCL 0x0002
 define STATUS 0x0003
 define FSR 0x0004
 define PORTA 0x0005
 define PORTB 0x0006
 define EEDATA 0x0008
 define EEADR 0x0009
 define PCLATH 0x000A
 define INTCON 0x000B

 define OPTION_REG 0x0081
 define TRISA 0x0085
 define TRISB 0x0086
 define EECON1 0x0088
 define EECON2 0x0089

 define IRP 0x0007
 define RP1 0x0006
 define RP0 0x0005
 define NOT_TO 0x0004
 define NOT_PD 0x0003
 define Z 0x0002
 define DC 0x0001
 define C 0x0000

 define GIE 0x0007
 define EEIE 0x0006
 define T0IE 0x0005
 define INTE 0x0004
 define RBIE 0x0003
 define T0IF 0x0002
 define INTF 0x0001
 define RBIF 0x0000

 define NOT_RBPU 0x0007
 define INTEDG 0x0006
 define T0CS 0x0005
 define T0SE 0x0004
 define PSA 0x0003
 define PS2 0x0002
 define PS1 0x0001
 define PS0 0x0000

 define EEIF 0x0004
 define WRERR 0x0003
 define WREN 0x0002
 define WR 0x0001
 define RD 0x0000

 define _CP_ON 0x000F
 define _CP_OFF 0x3FFF
 define _PWRTE_ON 0x3FF7
 define _PWRTE_OFF 0x3FFF
 define _WDT_ON 0x3FFF
 define _WDT_OFF 0x3FFB
 define _LP_OSC 0x3FFC
 define _XT_OSC 0x3FFD
 define _HS_OSC 0x3FFE
 define _RC_OSC 0x3FFF
 define __config 0x2007
