CC = wcc386
LD = wlink
RM = del

OBJS  = str.obj mem.obj arch.obj pic14b.obj as.obj main.obj misc.obj ihex.obj dis.obj

all: matpic.exe

.c.obj : .autodepend
	$(CC) $(CFLAGS) $<

matpic.exe: $(OBJS_MATPIC_AS)
	$(LD) name $@ file { $< }

clean: .symbolic
	$(RM) $(OBJS_MATPIC_AS) matpic.exe

