.\" sto manpage 
.\" copyright 2006 segin <segin2005@gmail.com>
.TH STO "1" "July 2006" "sto 1.0.1" "Segin's User Commands"
.SH NAME
sto \- A file archiver like tar.
.SH SYNOPSYS
.BR sto
.BR [c|x] 
.IR <archive>|- 
.IR file1,
.IR ...
.SH DESCRIPTION
.PP
.BR sto
is a file archiver that creates uncompress file archives that are similar
in design to those produced by 
.IR tar (1),
except that 
.BR sto
is incompatible with 
.IR tar (1). 
.PP
The
.BR sto
archiver takes at least 2 arguments to work. The first argument must be either
.BR c
or
.BR x ,
which start up 
.BR sto 
in either creation or extraction mode, respectively.
The second argument is a file to create or extract, or if 
.BR \- , 
use 
.IR stdin
or 
.IR stdout .
At this time, writing to 
.IR stdout
is unimplemented, and trying to do so will create a file
.BR \-
with the archive contents.
.BR sto ,
if invoked in creation mode, will add all files listed on the remainder of the command line to the archive. If 
.BR sto
was invoked in extraction mode, all extra arguments after the archive name are ignored.
.SH BUGS
Directory support has not been added. Also, there is no way to make sure that the file headers are actually 
.BR *valid*
file headers. Only a archive header check is preformed, and invalid file headers aren't checked for.
.SH AUTHOR
.BR sto
was written by Segin 
.IR <segin2005@gmail.com> ,
and all bug reports should be sent there.
.SH SEE ALSO
.IR tar (1)
