#
# kshell Makefile
# 

CC	:= gcc
CFLAGS	:= -Os
OBJEXT	:= .o
BINEXT	:= 
PROG	:= kshell


SOURCES	:= kshell.c
OBJS	:= $(SOURCES:.c=$(OBJEXT))

all: $(PROG)$(BINEXT)

$(PROG)$(BINEXT): $(OBJS)
