#
# Makefile for clockreset
#

# For UNIX

RM      = rm -f 
CC	=  cc
# Just add to, not replace CFLAGS
CFLAGS  += -Os 

# For Microsoft C:
# CC    = cl.exe
# RM    = del /y
# CFLAGS = # TODO: find CFLAGS for Microsoft C

# For MinGW:
# CC    = mingw32-gcc.exe
# RM    = rm -f  
# CFLAGS = -Os -pipe

clockreset: clockreset.c

clean: 
	$(RM) clockreset *.o *.obj 
